title: Aldi Satria
logo: /assets/img/logo.jpeg
description: Welcome to my cybersecurity portfolio! I focus on penetration testing, bug bounty hunting, and vulnerability research. This space showcases my projects, technical write-ups, and real-world security findings. I also share insights on my blog <a href="http://shatriyaa.blogspot.com">shatriyaa.blogspot.com</a>. Check out my work, and letâ€™s connect!
theme: jekyll-theme-minimal
